package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Options struct {
	AppName    string
	ModulePath string
}

func Generate(opts Options) (map[string]string, error) {
	if strings.TrimSpace(opts.AppName) == "" {
		return nil, fmt.Errorf("app name is required")
	}
	if strings.TrimSpace(opts.ModulePath) == "" {
		return nil, fmt.Errorf("module path is required")
	}

	appName := opts.AppName
	module := opts.ModulePath

	files := map[string]string{
		"go.mod":                                fmt.Sprintf("module %s\n\ngo 1.25.1\n\nrequire github.com/kusold/gotchi v0.1.0\n", module),
		"cmd/server/main.go":                    fmt.Sprintf("package main\n\nimport (\n\t\"context\"\n\t\"log\"\n\t\"os\"\n\n\t\"github.com/kusold/gotchi/app\"\n\t\"github.com/kusold/gotchi/db\"\n\t\"%s/internal/module\"\n\t\"%s/migrations\"\n)\n\nfunc main() {\n\tcfg := app.Config{\n\t\tServer: app.ServerConfig{Port: getenv(\"PORT\", \"3000\")},\n\t\tDatabase: db.Config{\n\t\t\tDatabaseURL: getenv(\"DATABASE_URL\", \"\"),\n\t\t},\n\t\tAuth: app.AuthConfig{},\n\t\tMigrations: app.MigrationConfig{\n\t\t\tEnableCore: true,\n\t\t\tEnableAuth: true,\n\t\t\tSources: []db.MigrationSource{{FS: migrations.Migrations, Dir: \".\"}},\n\t\t},\n\t}\n\n\tapplication, err := app.New(cfg, module.New())\n\tif err != nil {\n\t\tlog.Fatal(err)\n\t}\n\tlog.Fatal(application.Run(context.Background()))\n}\n\nfunc getenv(key, fallback string) string {\n\tif value := os.Getenv(key); value != \"\" {\n\t\treturn value\n\t}\n\treturn fallback\n}\n", module, module),
		"internal/module/module.go":             "package module\n\nimport (\n\t\"net/http\"\n\n\t\"github.com/go-chi/chi/v5\"\n\t\"github.com/kusold/gotchi/app\"\n)\n\ntype Module struct{}\n\nfunc New() Module { return Module{} }\n\nfunc (m Module) Register(r chi.Router, deps app.Dependencies) error {\n\tr.Get(\"/healthz\", func(w http.ResponseWriter, _ *http.Request) {\n\t\tw.WriteHeader(http.StatusOK)\n\t\t_, _ = w.Write([]byte(\"ok\"))\n\t})\n\treturn nil\n}\n",
		"migrations/migrations.go":              "package migrations\n\nimport \"embed\"\n\n//go:embed *.sql\nvar Migrations embed.FS\n",
		"migrations/20260101000000_example.sql": "-- +goose Up\n-- +goose StatementBegin\nCREATE TABLE IF NOT EXISTS example_records (\n\tid UUID PRIMARY KEY,\n\tname TEXT NOT NULL,\n\tcreated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n-- +goose StatementEnd\n\n-- +goose Down\n-- +goose StatementBegin\nDROP TABLE IF EXISTS example_records;\n-- +goose StatementEnd\n",
		".env.sample":                           "DATABASE_URL=postgres://pguser:pgpass@localhost:5432/\nPORT=3000\n\nOIDC_ISSUER_URL=\nOIDC_CLIENT_ID=\nOIDC_CLIENT_SECRET=\nOIDC_REDIRECT_URL=http://localhost:3000/auth/oidc/callback\nOIDC_TENANT_PICKER_PATH=/auth/tenants\nOIDC_POST_LOGIN_REDIRECT=/\n",
		"docker-compose.yaml":                   fmt.Sprintf("services:\n  db:\n    image: postgres:18\n    environment:\n      - POSTGRES_USER=pguser\n      - POSTGRES_PASSWORD=pgpass\n      - POSTGRES_DB=%s\n    ports:\n      - \"5432:5432\"\n", appName),
		"README.md":                             fmt.Sprintf("# %s\n\nGenerated by `gotchi init`.\n\n## Run\n\n1. Start postgres: `docker compose up -d db`\n2. Set env vars from `.env.sample`\n3. Run server: `go run ./cmd/server`\n", appName),
		".github/workflows/test.yaml":           "name: Tests\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-go@v5\n        with:\n          go-version: \"1.25.x\"\n      - run: go test ./...\n",
	}

	return files, nil
}

func Write(root string, files map[string]string) error {
	for path, content := range files {
		target := filepath.Join(root, path)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func FileList(files map[string]string) []string {
	list := make([]string, 0, len(files))
	for path := range files {
		list = append(list, path)
	}
	sort.Strings(list)
	return list
}
