package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Options struct {
	AppName    string
	ModulePath string
}

func Generate(opts Options) (map[string]string, error) {
	if strings.TrimSpace(opts.AppName) == "" {
		return nil, fmt.Errorf("app name is required")
	}
	if strings.TrimSpace(opts.ModulePath) == "" {
		return nil, fmt.Errorf("module path is required")
	}

	appName := opts.AppName
	module := opts.ModulePath

	files := map[string]string{
		"go.mod": fmt.Sprintf(`module %s

go 1.25.1

require github.com/kusold/gotchi v0.1.0
`, module),
		"cmd/server/main.go": fmt.Sprintf(`package main

import (
	"context"
	"log"
	"os"

	"github.com/kusold/gotchi/app"
	"github.com/kusold/gotchi/db"
	"%s/internal/module"
	"%s/migrations"
)

func main() {
	cfg := app.Config{
		Server: app.ServerConfig{Port: getenv("PORT", "3000")},
		Database: db.Config{
			DatabaseURL: getenv("DATABASE_URL", ""),
			Schema:      getenv("DB_SCHEMA", ""),
		},
		Auth: app.AuthConfig{},
		Migrations: app.MigrationConfig{
			EnableCore: true,
			EnableAuth: true,
			Sources: []db.MigrationSource{{FS: migrations.Migrations, Dir: "."}},
		},
	}

	application, err := app.New(cfg, module.New())
	if err != nil {
		log.Fatal(err)
	}
	log.Fatal(application.Run(context.Background()))
}

func getenv(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}
`, module, module),
		"internal/module/module.go": `package module

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/kusold/gotchi/app"
)

type Module struct{}

func New() Module { return Module{} }

func (m Module) Register(r chi.Router, deps app.Dependencies) error {
	r.Get("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	return nil
}
`,
		"migrations/migrations.go": `package migrations

import "embed"

//go:embed *.sql
var Migrations embed.FS
`,
		"migrations/20260101000000_example.sql": `-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS example_records (
	id UUID PRIMARY KEY,
	name TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS example_records;
-- +goose StatementEnd
`,
		".env.sample": `DATABASE_URL=postgres://pguser:pgpass@localhost:5432/` + appName + `
DB_SCHEMA=
PORT=3000

OIDC_ISSUER_URL=
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_REDIRECT_URL=http://localhost:3000/auth/oidc/callback
OIDC_TENANT_PICKER_PATH=/auth/tenants
OIDC_POST_LOGIN_REDIRECT=/
`,
		"docker-compose.yaml": `services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=` + appName + `
    ports:
      - "5432:5432"
`,
		"README.md": fmt.Sprintf(`# %s

Generated by `+"`gotchi init`"+`.

## Run

1. Start postgres: `+"`docker compose up -d db`"+`
2. Set env vars from `+"`.env.sample`"+`
3. Run server: `+"`go run ./cmd/server`"+`
`, appName),
		".github/workflows/test.yaml": `name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
      - run: go test ./...
`,
	}

	return files, nil
}

func Write(root string, files map[string]string) error {
	for path, content := range files {
		target := filepath.Join(root, path)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func FileList(files map[string]string) []string {
	list := make([]string, 0, len(files))
	for path := range files {
		list = append(list, path)
	}
	sort.Strings(list)
	return list
}
