package scaffold

import (
	"strings"
	"testing"
)

func TestGenerate(t *testing.T) {
	files, err := Generate(Options{AppName: "reference-app", ModulePath: "github.com/kusold/reference-app"})
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expected := []string{
		".env.sample",
		".github/workflows/test.yaml",
		"README.md",
		"cmd/server/main.go",
		"docker-compose.yaml",
		"go.mod",
		"internal/module/module.go",
		"migrations/20260101000000_example.sql",
		"migrations/migrations.go",
	}

	actual := FileList(files)
	if len(actual) != len(expected) {
		t.Fatalf("unexpected file count: got=%d want=%d", len(actual), len(expected))
	}
	for i := range expected {
		if actual[i] != expected[i] {
			t.Fatalf("unexpected file at %d: got=%s want=%s", i, actual[i], expected[i])
		}
	}

	if !strings.Contains(files["go.mod"], "module github.com/kusold/reference-app") {
		t.Fatalf("go.mod does not contain expected module path")
	}
	if !strings.Contains(files["cmd/server/main.go"], "application, err := app.New") {
		t.Fatalf("main template missing app.New bootstrap")
	}
	if !strings.Contains(files["README.md"], "Generated by `gotchi init`.") {
		t.Fatalf("README template missing init marker")
	}
}
