package scaffold

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerate(t *testing.T) {
	files, err := Generate(Options{AppName: "reference-app", ModulePath: "github.com/kusold/reference-app"})
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expected := []string{
		".env.sample",
		".github/workflows/test.yaml",
		"README.md",
		"cmd/server/main.go",
		"docker-compose.yaml",
		"go.mod",
		"internal/module/module.go",
		"migrations/20260101000000_example.sql",
		"migrations/migrations.go",
	}

	actual := FileList(files)
	if len(actual) != len(expected) {
		t.Fatalf("unexpected file count: got=%d want=%d", len(actual), len(expected))
	}
	for i := range expected {
		if actual[i] != expected[i] {
			t.Fatalf("unexpected file at %d: got=%s want=%s", i, actual[i], expected[i])
		}
	}

	if !strings.Contains(files["go.mod"], "module github.com/kusold/reference-app") {
		t.Fatalf("go.mod does not contain expected module path")
	}
	if !strings.Contains(files["cmd/server/main.go"], "application, err := app.New") {
		t.Fatalf("main template missing app.New bootstrap")
	}
	if !strings.Contains(files["README.md"], "Generated by `gotchi init`.") {
		t.Fatalf("README template missing init marker")
	}
}

func TestGenerate_RequiresAppName(t *testing.T) {
	tests := []struct {
		name    string
		appName string
	}{
		{"empty string", ""},
		{"whitespace only", "   "},
		{"tabs only", "\t\t"},
		{"newlines only", "\n\n"},
		{"mixed whitespace", " \t\n "},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := Generate(Options{AppName: tt.appName, ModulePath: "github.com/kusold/test"})
			if err == nil {
				t.Fatal("expected error for empty app name, got nil")
			}
			if !strings.Contains(err.Error(), "app name is required") {
				t.Fatalf("unexpected error message: %v", err)
			}
		})
	}
}

func TestGenerate_RequiresModulePath(t *testing.T) {
	tests := []struct {
		name       string
		modulePath string
	}{
		{"empty string", ""},
		{"whitespace only", "   "},
		{"tabs only", "\t\t"},
		{"newlines only", "\n\n"},
		{"mixed whitespace", " \t\n "},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := Generate(Options{AppName: "test-app", ModulePath: tt.modulePath})
			if err == nil {
				t.Fatal("expected error for empty module path, got nil")
			}
			if !strings.Contains(err.Error(), "module path is required") {
				t.Fatalf("unexpected error message: %v", err)
			}
		})
	}
}

func TestWrite(t *testing.T) {
	t.Parallel()

	files := map[string]string{
		"file.txt":              "content",
		"subdir/nested.txt":     "nested content",
		"deep/path/to/file.txt": "deep content",
	}

	root := t.TempDir()

	err := Write(root, files)
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}

	// Verify all files were written correctly
	for path, expectedContent := range files {
		target := filepath.Join(root, path)
		data, err := os.ReadFile(target)
		if err != nil {
			t.Fatalf("failed to read %s: %v", path, err)
		}
		if string(data) != expectedContent {
			t.Fatalf("content mismatch for %s: got=%q want=%q", path, string(data), expectedContent)
		}
	}
}

func TestWrite_EmptyFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	err := Write(root, map[string]string{})
	if err != nil {
		t.Fatalf("Write with empty files returned error: %v", err)
	}
}

func TestWrite_OverwritesExisting(t *testing.T) {
	t.Parallel()

	root := t.TempDir()

	// Write initial file
	files1 := map[string]string{"test.txt": "initial"}
	if err := Write(root, files1); err != nil {
		t.Fatalf("first Write returned error: %v", err)
	}

	// Overwrite with new content
	files2 := map[string]string{"test.txt": "updated"}
	if err := Write(root, files2); err != nil {
		t.Fatalf("second Write returned error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(root, "test.txt"))
	if err != nil {
		t.Fatalf("failed to read file: %v", err)
	}
	if string(data) != "updated" {
		t.Fatalf("file not overwritten: got=%q want=%q", string(data), "updated")
	}
}

func TestWrite_CreatesMultipleDirectoryLevels(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	files := map[string]string{
		"a/b/c/d/e/file.txt": "deeply nested",
	}

	if err := Write(root, files); err != nil {
		t.Fatalf("Write returned error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(root, "a/b/c/d/e/file.txt"))
	if err != nil {
		t.Fatalf("failed to read deeply nested file: %v", err)
	}
	if string(data) != "deeply nested" {
		t.Fatalf("unexpected content: got=%q", string(data))
	}
}

func TestFileList(t *testing.T) {
	t.Parallel()

	files := map[string]string{
		"c.txt": "",
		"a.txt": "",
		"b.txt": "",
		"d.txt": "",
	}

	list := FileList(files)

	expected := []string{"a.txt", "b.txt", "c.txt", "d.txt"}
	if len(list) != len(expected) {
		t.Fatalf("unexpected length: got=%d want=%d", len(list), len(expected))
	}

	for i, path := range expected {
		if list[i] != path {
			t.Fatalf("file at index %d: got=%s want=%s", i, list[i], path)
		}
	}
}

func TestFileList_Empty(t *testing.T) {
	t.Parallel()

	list := FileList(map[string]string{})
	if len(list) != 0 {
		t.Fatalf("expected empty list, got %d items", len(list))
	}
}

func TestFileList_SortedOrder(t *testing.T) {
	t.Parallel()

	files := map[string]string{
		"zebra.txt":   "",
		"alpha.txt":   "",
		"beta.txt":    "",
		"gamma.txt":   "",
		"123.txt":     "",
		"UPPER.txt":   "",
		"lower.txt":  "",
		"with/path.txt": "",
	}

	list := FileList(files)

	// Verify the list is sorted
	for i := 1; i < len(list); i++ {
		if list[i-1] > list[i] {
			t.Fatalf("list not sorted at index %d: %q > %q", i-1, list[i-1], list[i])
		}
	}
}

func TestGenerate_ContentSubstitution(t *testing.T) {
	files, err := Generate(Options{AppName: "my-app", ModulePath: "github.com/example/my-app"})
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	// Check app name is used in expected places
	if !strings.Contains(files[".env.sample"], "my-app") {
		t.Fatal(".env.sample should contain app name")
	}
	if !strings.Contains(files["docker-compose.yaml"], "my-app") {
		t.Fatal("docker-compose.yaml should contain app name")
	}
	if !strings.Contains(files["README.md"], "# my-app") {
		t.Fatal("README.md should have app name as title")
	}

	// Check module path is used
	if !strings.Contains(files["go.mod"], "module github.com/example/my-app") {
		t.Fatal("go.mod should have correct module path")
	}
	if !strings.Contains(files["cmd/server/main.go"], "github.com/example/my-app/internal/module") {
		t.Fatal("main.go should import internal module with correct path")
	}
}
