// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFirstTenant = `-- name: GetFirstTenant :one
SELECT tenant_id
FROM tenants
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetFirstTenant(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFirstTenant)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const getMembershipByUserAndTenant = `-- name: GetMembershipByUserAndTenant :one
SELECT tenant_id, role
FROM tenant_memberships
WHERE user_id = $1 AND tenant_id = $2
`

type GetMembershipByUserAndTenantParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetMembershipByUserAndTenantRow struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Role     string    `json:"role"`
}

func (q *Queries) GetMembershipByUserAndTenant(ctx context.Context, arg GetMembershipByUserAndTenantParams) (GetMembershipByUserAndTenantRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserAndTenant, arg.UserID, arg.TenantID)
	var i GetMembershipByUserAndTenantRow
	err := row.Scan(&i.TenantID, &i.Role)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT tenant_id, name
FROM tenants
WHERE tenant_id = $1
`

type GetTenantByIDRow struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) GetTenantByID(ctx context.Context, tenantID uuid.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i GetTenantByIDRow
	err := row.Scan(&i.TenantID, &i.Name)
	return i, err
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one
SELECT
    id,
    issuer,
    identifier_subject
FROM users
WHERE issuer = $1 AND identifier_subject = $2
`

type GetUserByIdentifierParams struct {
	Issuer            string `json:"issuer"`
	IdentifierSubject string `json:"identifier_subject"`
}

type GetUserByIdentifierRow struct {
	ID                uuid.UUID `json:"id"`
	Issuer            string    `json:"issuer"`
	IdentifierSubject string    `json:"identifier_subject"`
}

func (q *Queries) GetUserByIdentifier(ctx context.Context, arg GetUserByIdentifierParams) (GetUserByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, arg.Issuer, arg.IdentifierSubject)
	var i GetUserByIdentifierRow
	err := row.Scan(&i.ID, &i.Issuer, &i.IdentifierSubject)
	return i, err
}

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO tenants (tenant_id, name)
VALUES ($1, $2)
`

type InsertTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant, arg.TenantID, arg.Name)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    id,
    email,
    email_verified,
    username,
    name,
    issuer,
    identifier_subject,
    last_login_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, issuer, identifier_subject
`

type InsertUserParams struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	EmailVerified     bool               `json:"email_verified"`
	Username          pgtype.Text        `json:"username"`
	Name              pgtype.Text        `json:"name"`
	Issuer            string             `json:"issuer"`
	IdentifierSubject string             `json:"identifier_subject"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
}

type InsertUserRow struct {
	ID                uuid.UUID `json:"id"`
	Issuer            string    `json:"issuer"`
	IdentifierSubject string    `json:"identifier_subject"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.Username,
		arg.Name,
		arg.Issuer,
		arg.IdentifierSubject,
		arg.LastLoginAt,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.Issuer, &i.IdentifierSubject)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT
    tm.tenant_id,
    t.name AS tenant_name,
    tm.role
FROM tenant_memberships tm
JOIN tenants t ON t.tenant_id = tm.tenant_id
WHERE tm.user_id = $1
ORDER BY tm.created_at
`

type ListMembershipsRow struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	TenantName string    `json:"tenant_name"`
	Role       string    `json:"role"`
}

func (q *Queries) ListMemberships(ctx context.Context, userID uuid.UUID) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsRow
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(&i.TenantID, &i.TenantName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO tenant_memberships (user_id, tenant_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, tenant_id)
DO UPDATE SET role = EXCLUDED.role
RETURNING tenant_id, role
`

type UpsertMembershipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Role     string    `json:"role"`
}

type UpsertMembershipRow struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Role     string    `json:"role"`
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (UpsertMembershipRow, error) {
	row := q.db.QueryRow(ctx, upsertMembership, arg.UserID, arg.TenantID, arg.Role)
	var i UpsertMembershipRow
	err := row.Scan(&i.TenantID, &i.Role)
	return i, err
}
