// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
UPDATE auth_tokens
SET consumed_at = NOW()
WHERE token_hash = $1
  AND token_type = $2
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING user_id
`

type ConsumeAuthTokenParams struct {
	TokenHash []byte `json:"token_hash"`
	TokenType string `json:"token_type"`
}

func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAuthToken, arg.TokenHash, arg.TokenType)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const countRecentFailedAttempts = `-- name: CountRecentFailedAttempts :one
SELECT COUNT(*)
FROM login_attempts
WHERE user_id = $1
  AND success = FALSE
  AND attempted_at > $2
`

type CountRecentFailedAttemptsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AttemptedAt time.Time `json:"attempted_at"`
}

func (q *Queries) CountRecentFailedAttempts(ctx context.Context, arg CountRecentFailedAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedAttempts, arg.UserID, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePasswordCredential = `-- name: DeletePasswordCredential :exec
DELETE FROM password_credentials
WHERE user_id = $1
`

func (q *Queries) DeletePasswordCredential(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordCredential, userID)
	return err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one

SELECT user_id, password_hash, hash_algorithm, created_at, updated_at
FROM password_credentials
WHERE user_id = $1
`

// Password authentication queries for sqlc code generation.
func (q *Queries) GetPasswordCredential(ctx context.Context, userID uuid.UUID) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredential, userID)
	var i PasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.HashAlgorithm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailAndIssuer = `-- name: GetUserByEmailAndIssuer :one
SELECT id, email, email_verified, username, name, issuer, identifier_subject, last_login_at, created_at, updated_at
FROM users
WHERE email = $1 AND issuer = $2
`

type GetUserByEmailAndIssuerParams struct {
	Email  string `json:"email"`
	Issuer string `json:"issuer"`
}

func (q *Queries) GetUserByEmailAndIssuer(ctx context.Context, arg GetUserByEmailAndIssuerParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAndIssuer, arg.Email, arg.Issuer)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Username,
		&i.Name,
		&i.Issuer,
		&i.IdentifierSubject,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, username, name, issuer, identifier_subject, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Username,
		&i.Name,
		&i.Issuer,
		&i.IdentifierSubject,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuthToken = `-- name: InsertAuthToken :exec
INSERT INTO auth_tokens (user_id, token_hash, token_type, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertAuthTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	TokenType string    `json:"token_type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) error {
	_, err := q.db.Exec(ctx, insertAuthToken,
		arg.UserID,
		arg.TokenHash,
		arg.TokenType,
		arg.ExpiresAt,
	)
	return err
}

const invalidateUserTokens = `-- name: InvalidateUserTokens :exec
UPDATE auth_tokens
SET consumed_at = NOW()
WHERE user_id = $1
  AND token_type = $2
  AND consumed_at IS NULL
`

type InvalidateUserTokensParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenType string    `json:"token_type"`
}

func (q *Queries) InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateUserTokens, arg.UserID, arg.TokenType)
	return err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (user_id, ip_address, success)
VALUES ($1, $2, $3)
`

type RecordLoginAttemptParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	IpAddress *netip.Addr `json:"ip_address"`
	Success   bool        `json:"success"`
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLoginAttempt, arg.UserID, arg.IpAddress, arg.Success)
	return err
}

const updateEmailVerified = `-- name: UpdateEmailVerified :exec
UPDATE users
SET email_verified = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateEmailVerified, id)
	return err
}

const updateLastLoginAt = `-- name: UpdateLastLoginAt :exec
UPDATE users
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLoginAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLoginAt, id)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE password_credentials
SET password_hash = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdatePasswordHashParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.UserID, arg.PasswordHash)
	return err
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO password_credentials (user_id, password_hash, hash_algorithm)
VALUES ($1, $2, $3)
ON CONFLICT (user_id)
DO UPDATE SET password_hash = EXCLUDED.password_hash,
              hash_algorithm = EXCLUDED.hash_algorithm,
              updated_at = NOW()
`

type UpsertPasswordCredentialParams struct {
	UserID        uuid.UUID `json:"user_id"`
	PasswordHash  string    `json:"password_hash"`
	HashAlgorithm string    `json:"hash_algorithm"`
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordCredential, arg.UserID, arg.PasswordHash, arg.HashAlgorithm)
	return err
}
