// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetFirstTenant(ctx context.Context) (uuid.UUID, error)
	GetMembershipByUserAndTenant(ctx context.Context, arg GetMembershipByUserAndTenantParams) (GetMembershipByUserAndTenantRow, error)
	GetTenantByID(ctx context.Context, tenantID uuid.UUID) (GetTenantByIDRow, error)
	GetUserByIdentifier(ctx context.Context, arg GetUserByIdentifierParams) (GetUserByIdentifierRow, error)
	InsertTenant(ctx context.Context, arg InsertTenantParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error)
	ListMemberships(ctx context.Context, userID uuid.UUID) ([]ListMembershipsRow, error)
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (UpsertMembershipRow, error)
}

var _ Querier = (*Queries)(nil)
